### ISSUE TITLE
Move water property tables and routines to Futility

### ISSUE THREAD

**Issue by zdodson94** [CASL/Futility#108]
To facilitate calculation of moderator density as a function of temperature for moderator temperature conservatism, water property tables and routines should be moved from FluidFlow to Futility.

The moderator temperature is scaled from within XSMesh when moderator temperature conservatism is enabled, so moving this to Futility would allow for the new density to be calculated from within XSMesh and provide more realistic results.

**Comment by bscollin** [comment]
This has been addressed with PR #315
