### ISSUE TITLE
No mechanism for building code or documentation without MPACT

### ISSUE THREAD

**Issue by youngmit** [CASL/Futility#15]
The Doxygen documentation was previously being built under the MPACT doxygen file as part of the whole MPACT documentation. Following the split, there is no mechanism to generate standalone Futility documentation, nor does it get built my the MPACT documentation.

**Comment by bscollin** [comment]
I'm extending this.  There's no mechanism to build Futility standalone either.

**Comment by bscollin** [comment]
Pull request #16 handles building the code.  The documentation should be pretty straightforward.

**Comment by bscollin** [comment]
Should be working now
