### ISSUE TITLE
Futility doesn't build with PETSC enabled and MPI disabled

### ISSUE THREAD

**Issue by tghaddar** [CASL/Futility#241]
I tried to build Futility (as part of MPACT) with PETSC enabled and MPI disabled, and ended up with an " mpi.h: No such file or directory" error message.

**Comment by aarograh** [comment]
Should it?  Is this something that we want to do or that petsc should be able to do?

**Comment by bscollin** [comment]
This is likely because when we build the PETSC TPL, its with MPI on.  I think we'd need to configure PETSC in serial but also, I'm certain Futility would need to change to not assume PETSC on = MPI on.

**Comment by stimpsonsg** [comment]
At a minimum, I would think we would need to catch this at configuration.
