### ISSUE TITLE
Merge request Travis CI failure due to invalid Trilinos git repo

### ISSUE THREAD

**Issue by KyleVaughn** [CASL/Futility#320]
My most recent CI run after push to a branch (XDMF) with an open merge request failed. Found [here](https://travis-ci.org/github/CASL/Futility/builds/764578235). I believe it was due to the following:
```
git clone https://github.com/CASL/Trilinos.git
Cloning into 'Trilinos'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/CASL/Trilinos.git/'
The command "git clone https://github.com/CASL/Trilinos.git" exited with 128.
```
The Github [Trilinos](https://github.com/CASL/Trilinos) does not exist at that address, so the build script probably just needs an update with the correct address or credential if the repo is private.

**Comment by aarograh** [comment]
@KyleVaughn this should be fixed now.  Ben created a new Trilinos repo on github.  Next time you push something up, comment here to let me know if the CI worked or not.  If it does, we can close this issue

**Comment by KyleVaughn** [comment]
@aarograh sounds good. Do you know if I can rerun CI on my current commit, or do I have to push another for it to run? If so, I'll just push an empty commit real fast.

**Comment by aarograh** [comment]
In theory you can restart travis-ci builds, but I've been trying and it just keeps giving me an error.  An empty commit or some small little cleanup of some sort would be fine to trigger a fresh build.

**Comment by KyleVaughn** [comment]
Looks like the CI worked. Good to close.

**Comment by aarograh** [comment]
Cool, thanks.
