### ISSUE TITLE
Add attribute support to the HDF file type

### ISSUE THREAD

**Issue by youngmit** [CASL/Futility#34]
The current HDF interface does not provide access to the attribute features of the HDF5 library/format. It would be nice to be able to add, at the very least, scalar key-value pairs as attributes to HDF5 datasets.

**Comment by youngmit** [comment]
We at least want to support writing scalar strings, integers and floats. We can add reading capability and support for arrays as-needed later

**Comment by bscollin** [comment]
Just checked and it looks like CTF only supports writing scalar strings, ints, and doubles.

**Comment by youngmit** [comment]
Yeah, we noticed that as well. Not a bad place to start, though. I don't like how they use optional arguments to select the type of the attribute, and recommend using a generic interface like the rest of the existing Futility HDF5 interfaces

**Comment by bscollin** [comment]
This should be closed per #37
