### ISSUE TITLE
FileType_HDF5 does not offer a means of overwriting existing datasets

### ISSUE THREAD

**Issue by rks171** [CASL/Futility#74]
The write methods all call preWrite.  preWrite will always attempt to create the dataset that the user passed in.  If it already exists in the HDF5 file, the HDF5 interface will throw an error.  Sometimes we need to overwrite existing datasets (e.g., CTF needs to overwrite pin_powers when CTF_save_simple_restart is called).  We can make a new method (overwrite) that does the same thing as 'write' but skips the dataset creation when it already exists, but this will add a lot of stuff to the class.  We could also just make 'write' default to overwriting and leave it to the user to check if the dataset already exists if they are worried about overwriting it.

**Comment by bkochuna** [comment]
Another option is to add an optional argument to the write interface to indicate if the the user wants to overwrite the data set or not.

That approach would still be a pain to implement (every write interface in the module would need to be updated) and then the preWrite interface would need to be updated. Given that, this still might be the way to go. I certainly think this approach is better than adding an overwrite method (and doesn't preclude that in the future).

And personally, this is probably the approach I would favor. I think its a little "safer" than just changing preWrite to overwrite. But that is certainly the approach with the least effort.

**Comment by bscollin** [comment]
I'm a little more in favor of Bob's approach where when we "open" the file, we state the protection of the data.  It reduces the interface for WRITE but I also think that that is generally the way we would approach editing a file, either we don't care whats in it, or it needs to be protected.  In principle we can implement both approaches.  You can make the complete file over-writeable or you can make it write-only, but the write statement will still allow you to tell it to overwrite data.  Just a suggestion.

**Comment by bkochuna** [comment]
Yeah, that is better. Didn't get that approach from Bob's original comment.

**Comment by bscollin** [comment]
Just took both of your ideas and combined them ;-)

**Comment by rks171** [comment]
Yeah, that wasn't really my original idea, but I think it's a good one.  When I wrote the HDF5 stub in CTF, I did it how Brendan suggested, making an optional argument to allow overwrite that defaults to off.  In practice, I always just ended up including the argument when calling the procedure and setting it to .true., because each coupled iteration, we want to overwrite all the solution datasets.  So I think being able to make the file over-writeable from the beginning would lessen that burden a bit.  

So to clarify, the hdf5 init currently takes 'READ', 'WRITE', or 'NEW'.  Are you thinking just add an additional option, 'OVERWRITE'/'OVERWRITABLE', or create a new method that allows the user to toggle the overwrite status?

**Comment by bscollin** [comment]
Lets target this in two phases.
 * Phase 1:  Implement the global approach where you can define 'WRITE' or "OVERWRITE', get that into the main code, then
 * Phase 2:  Get someone to go through and add an optional input to all of the write statements that modifies the prewrite (probably a lower priority).

**Comment by rks171** [comment]
Just realizing as I code this up, a user can not overwrite an existing dataset if the size or type of the new one differs from the old one.  HDF5 does not offer a way to delete a dataset, either, as far as I know.  It can be unlinked, but you don't get the space back.  So I'm thinking we want to document this limitation and leave it as an exception?

**Comment by bscollin** [comment]
I'm thinking if the shape is different we just stop.  Not a big fan of leaving unlinked data around.

**Comment by bscollin** [comment]
This was addressed in merge request #95.  Closing as fixed.
